version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: webstore_449
      POSTGRES_USER: webstore_user
      POSTGRES_PASSWORD: webstore_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
